# Generated by Django 3.2.3 on 2021-05-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seoul_road',
            new_name='SeoulRoad',
        ),
    ]
