# Generated by Django 3.2.3 on 2021-05-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_rename_seoul_road_seoulroad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeoulRoad',
            new_name='Road',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
