# Generated by Django 3.2.3 on 2021-05-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fire_loc', models.CharField(max_length=200)),
                ('Fire_time', models.DateTimeField()),
                ('Fire_state', models.CharField(max_length=200)),
                ('Fire_area', models.CharField(max_length=10)),
            ],
        ),
    ]
