# Generated by Django 3.2.3 on 2021-05-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('idx', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('url', models.CharField(max_length=150)),
            ],
        ),
    ]
