# Generated by Django 3.2.3 on 2021-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unknown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='idx',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
