# Generated by Django 3.2.3 on 2021-06-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unknown', '0002_alter_record_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='nickname',
            field=models.CharField(default='unknown', max_length=12),
        ),
    ]
