# Generated by Django 3.2.3 on 2021-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unknown', '0003_record_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='video_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
