# Generated by Django 3.2.3 on 2021-06-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unknown', '0004_record_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='gender',
        ),
    ]
